name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'windows'
          - os: ubuntu-22.04
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'
          - os: macos-12
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Run Maven install
        shell: bash
        run: mvn clean install
